name: program # Sebaiknya ganti dengan nama yang lebih deskriptif, misal: jastip_app
description: "Aplikasi Jasa Titip dengan Fitur Live Shopping (Skripsi)." # Deskripsi yang lebih jelas
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# ... (komentar bawaan tentang versioning tetap sama) ...
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Menggunakan Dart 3 atau lebih baru (sesuai permintaan sebelumnya)

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Jika butuh dukungan multi-bahasa
    sdk: flutter

  # --- Firebase Core & Services ---
  firebase_core: ^3.13.0      # Wajib untuk semua project Firebase
  firebase_auth: ^5.6.2      # Untuk Autentikasi (Login, Register)
  cloud_firestore: ^5.6.7    # Database NoSQL Firestore
  firebase_storage: ^12.4.5     # Untuk menyimpan file (gambar/video)
  firebase_messaging: ^15.2.10   # Untuk Push Notifications (FCM)
  cloud_functions: ^5.5.0   # Diganti ke versi yang kompatibel dengan firebase_core ^2.32.0
  # --- State Management (Riverpod) ---
  flutter_riverpod: ^2.6.1     # State management utama
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5  # (Opsional tapi direkomendasikan) Anotasi untuk code generation Riverpod
  hmssdk_flutter: ^1.10.6
  path_provider: ^2.1.5
  

  # --- Navigation ---
  go_router: ^15.1.2          # (Direkomendasikan) Untuk routing terstruktur
  # --- Networking ---
  dio: ^5.4.3+1               # HTTP client untuk memanggil API

  # --- Live Shopping (100ms) ---
   # SDK resmi dari 100ms untuk Flutter (cek versi terbaru di dokumentasi 100ms)

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8     # Ikon standar iOS (sudah ada)
  intl: ^0.19.0               # Untuk formatting (tanggal, angka, mata uang) & i18n
  equatable: ^2.0.7           # Memudahkan perbandingan objek
  image_picker: ^1.1.2      # Memilih gambar dari galeri/kamera
  cached_network_image: ^3.4.1 # Menampilkan & cache gambar dari network
  uuid: ^4.4.0                # Membuat ID unik
  url_launcher: ^6.3.0        # Membuka URL eksternal

  # --- Data Models & Immutability (Direkomendasikan) ---
  freezed_annotation: ^3.0.0   # Anotasi untuk Freezed (code generation model/state)
  cloudinary_flutter: ^1.3.0
  cloudinary_url_gen: ^1.7.0
  cloudinary_sdk: ^5.0.0+1
  cloudinary_public: ^0.21.0
  http: ^1.5.0
  permission_handler: ^12.0.1
  video_thumbnail: ^0.5.6
  webview_flutter: ^4.13.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.4.11        # Runner untuk menjalankan code generators
  freezed: ^3.0.6              # Generator untuk membuat data class immutable (models, states)
  riverpod_generator: ^2.4.0   # (Opsional tapi direkomendasikan) Generator untuk providers Riverpod
  # go_router_builder: ^2.7.0  # Jika ingin generate route dari GoRouter (tambahkan jika perlu)

  # --- Linting ---
  # Paket ini mendorong praktik pengkodean yang baik.
  flutter_lints: ^5.0.0       # Aturan linting standar (sudah ada)

  # --- Testing ---
  mocktail: ^1.0.3            # Framework mocking modern untuk testing

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/logo.png # Contoh: Tambahkan folder assets Anda di sini nanti
  #   - assets/icons/
  #   - assets/fonts/

  # ... (bagian fonts tetap sama) ...
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700