name: program # Sebaiknya ganti dengan nama yang lebih deskriptif, misal: jastip_app
description: "Aplikasi Jasa Titip dengan Fitur Live Shopping (Skripsi)." # Deskripsi yang lebih jelas
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# ... (komentar bawaan tentang versioning tetap sama) ...
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Menggunakan Dart 3 atau lebih baru (sesuai permintaan sebelumnya)

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Jika butuh dukungan multi-bahasa
    sdk: flutter

  # --- Firebase Core & Services ---
  firebase_core: ^2.32.0      # Wajib untuk semua project Firebase
  firebase_auth: ^4.20.0      # Untuk Autentikasi (Login, Register)
  cloud_firestore: ^4.17.5    # Database NoSQL Firestore
  firebase_storage: ^11.7.7     # Untuk menyimpan file (gambar/video)
  firebase_messaging: ^14.9.4   # Untuk Push Notifications (FCM)
  firebase_functions: ^4.8.3    # Untuk memanggil Cloud Functions

  # --- State Management (Riverpod) ---
  flutter_riverpod: ^2.5.1     # State management utama
  riverpod_annotation: ^2.3.5  # (Opsional tapi direkomendasikan) Anotasi untuk code generation Riverpod

  # --- Navigation ---
  go_router: ^14.1.0          # (Direkomendasikan) Untuk routing terstruktur

  # --- Networking ---
  dio: ^5.4.3+1               # HTTP client untuk memanggil API

  # --- Live Shopping (100ms) ---
   # SDK resmi dari 100ms untuk Flutter (cek versi terbaru di dokumentasi 100ms)

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8     # Ikon standar iOS (sudah ada)
  intl: ^0.19.0               # Untuk formatting (tanggal, angka, mata uang) & i18n
  equatable: ^2.0.5           # Memudahkan perbandingan objek
  image_picker: ^1.1.2        # Memilih gambar dari galeri/kamera
  cached_network_image: ^3.3.1 # Menampilkan & cache gambar dari network
  uuid: ^4.4.0                # Membuat ID unik
  url_launcher: ^6.3.0        # Membuka URL eksternal

  # --- Data Models & Immutability (Direkomendasikan) ---
  freezed_annotation: ^2.4.1   # Anotasi untuk Freezed (code generation model/state)

dev_dependencies:
  flutter_test:
    sdk: flutter

  # --- Code Generation ---
  build_runner: ^2.4.11        # Runner untuk menjalankan code generators
  freezed: ^2.5.2              # Generator untuk membuat data class immutable (models, states)
  riverpod_generator: ^2.4.0   # (Opsional tapi direkomendasikan) Generator untuk providers Riverpod
  # go_router_builder: ^2.7.0  # Jika ingin generate route dari GoRouter (tambahkan jika perlu)

  # --- Linting ---
  # Paket ini mendorong praktik pengkodean yang baik.
  flutter_lints: ^4.0.0       # Aturan linting standar (sudah ada)

  # --- Testing ---
  mocktail: ^1.0.3            # Framework mocking modern untuk testing

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - assets/images/logo.png # Contoh: Tambahkan folder assets Anda di sini nanti
  #   - assets/icons/
  #   - assets/fonts/

  # ... (bagian fonts tetap sama) ...
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700