// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOpFdGlZC3ZxryisOgHeZH6zW3VKWcXjw',
    appId: '1:730172618870:android:0c4145d6a8569d4bf98757',
    messagingSenderId: '730172618870',
    projectId: 'ta-ngoper',
    storageBucket: 'ta-ngoper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kJvRkSSDWg0Mj6eVaBJeOMaxo7c2h8k',
    appId: '1:730172618870:ios:ad0dc8828575c976f98757',
    messagingSenderId: '730172618870',
    projectId: 'ta-ngoper',
    storageBucket: 'ta-ngoper.firebasestorage.app',
    iosBundleId: 'com.example.program',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcp5LEZCuTiJPKPw072u7lofLn8XLjdPk',
    appId: '1:730172618870:web:49eb5514d8d45845f98757',
    messagingSenderId: '730172618870',
    projectId: 'ta-ngoper',
    authDomain: 'ta-ngoper.firebaseapp.com',
    storageBucket: 'ta-ngoper.firebasestorage.app',
    measurementId: 'G-3YCC32DJSP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2kJvRkSSDWg0Mj6eVaBJeOMaxo7c2h8k',
    appId: '1:730172618870:ios:ad0dc8828575c976f98757',
    messagingSenderId: '730172618870',
    projectId: 'ta-ngoper',
    storageBucket: 'ta-ngoper.firebasestorage.app',
    iosBundleId: 'com.example.program',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcp5LEZCuTiJPKPw072u7lofLn8XLjdPk',
    appId: '1:730172618870:web:251fcaf0513dcab9f98757',
    messagingSenderId: '730172618870',
    projectId: 'ta-ngoper',
    authDomain: 'ta-ngoper.firebaseapp.com',
    storageBucket: 'ta-ngoper.firebasestorage.app',
    measurementId: 'G-PSF7PSZ4TR',
  );

}